services:
  db:
    image: postgres:17
    container_name: minitrello_db_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=minitrello
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  backend:
    build: .
    container_name: minitrello_backend_container
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=MiniTrello.settings
      - DEBUG=True


  redis:
    image: redis:7-alpine # Using the lightweight Alpine version
    container_name: minitrello_redis_container
    ports:
      - "6379:6379"


  celery_worker:
    build: .
    container_name: minitrello_celery_worker
    command: celery -A MiniTrello worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis # The worker also needs the DB and Redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.development
      - DEBUG=True
